using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using HarmonyLib;
using ScriptEngine;

namespace SFR.API;

/// <summary>
/// For unknown reasons scripts won't work in SFR. This class fixes them.
/// Most likely it's due to the strong assembly signing of Superfighters Deluxe.exe
/// which SFR breaks, thus the script engine won't recognize it at all.
/// </summary>
[HarmonyPatch(typeof(Sandbox))]
internal static class Engine
{
    private static readonly Dictionary<Sandbox, AppDomain> _appDomains = [];

    [HarmonyPrefix]
    [HarmonyPatch(nameof(Sandbox.Create))]
    private static bool Create(ref Sandbox __result)
    {
        string applicationBase = AppDomain.CurrentDomain.SetupInformation.ApplicationBase;
        string dynamicBase = Path.Combine(applicationBase, "SFR", "ScriptCache");
        AppDomainSetup info = new()
        {
            ApplicationBase = applicationBase,
            ApplicationName = "Sandbox",
            DisallowBindingRedirects = false,
            DisallowCodeDownload = true,
            DisallowPublisherPolicy = true,
            ShadowCopyFiles = "false",
            DynamicBase = dynamicBase,
            ConfigurationFile = AppDomain.CurrentDomain.SetupInformation.ConfigurationFile
        };

        AppDomain appDomain = AppDomain.CreateDomain("Sandbox", null, info);
        Sandbox sandbox = (Sandbox)Activator.CreateInstanceFrom(appDomain, typeof(Sandbox).Assembly.ManifestModule.FullyQualifiedName, typeof(Sandbox).FullName).Unwrap();

        sandbox.Setup();

        _appDomains.Add(sandbox, appDomain);

        __result = sandbox;
        return false;
    }

    [HarmonyPrefix]
    [HarmonyPatch(nameof(Sandbox.Unload))]
    private static bool Unload(Sandbox sandbox)
    {
        if (_appDomains.ContainsKey(sandbox))
        {
            AppDomain domain = _appDomains[sandbox];
            sandbox.Dispose();
            _ = _appDomains.Remove(sandbox);
            AppDomain.Unload(domain);
        }

        return false;
    }
}

/// <summary>
/// Patches CompilerResults to load compiled script assemblies from memory (byte array)
/// instead of from file. This bypasses Windows Smart App Control (WDAC) which blocks
/// unsigned temporary assemblies (tmpXXXX.tmp) generated by CSharpCodeProvider.
/// </summary>
[HarmonyPatch(typeof(CompilerResults), nameof(CompilerResults.CompiledAssembly), MethodType.Getter)]
internal static class ScriptCompilerPatch
{
    private static readonly FieldInfo _compiledAssemblyField =
        typeof(CompilerResults).GetField("compiledAssembly", BindingFlags.NonPublic | BindingFlags.Instance);

    private static bool Prefix(CompilerResults __instance, ref Assembly __result)
    {
        var assembly = (Assembly)_compiledAssemblyField?.GetValue(__instance);

        if (assembly == null && __instance.PathToAssembly != null && File.Exists(__instance.PathToAssembly))
        {
            // Load assembly from raw bytes to avoid WDAC file-based signature checks.
            byte[] rawAssembly = File.ReadAllBytes(__instance.PathToAssembly);
            assembly = Assembly.Load(rawAssembly);
            _compiledAssemblyField?.SetValue(__instance, assembly);
        }

        __result = assembly;
        return false;
    }
}